#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const commander = require('./lib/commander/index');
const mkdirp = require('./lib/mkdirp/index');
const validationFunctionLoader = require('./src/loading/validation-function-loader');

const errorStatus = 1;

const { version } = require('./package');

// Parse the commandline arguments
commander.arguments('<document_definitions_file> <output_file>')
  .version(version, '-v, --version')
  .description('A utility for generating document validation functions for Apache CouchDB.')
  .option('-j, --json-string', 'enclose the validation function contents in a JSON-compatible string');

commander.on('--help', () => {
  // Add some extra information after the main body of the usage/help text
  console.info(`
  For example: ${commander.name()} /path/to/my-doc-definitions.js /path/to/my-new-validation-function.js

  See the README for more information.`);
});

commander.parse(process.argv);

if (commander.args.length !== 2) {
  commander.outputHelp();

  process.exit(errorStatus);
}

const docDefnFilename = commander.args[0];
const outputFilename = commander.args[1];

let validationFuncString;
try {
  const formatOptions = { jsonString: commander.jsonString };
  validationFuncString = validationFunctionLoader.load(docDefnFilename, formatOptions);
} catch (ex) {
  process.exit(errorStatus);
}

try {
  const outputDirectory = path.dirname(outputFilename);
  if (!fs.existsSync(outputDirectory)) {
    mkdirp.sync(outputDirectory);
  }
} catch (ex) {
  console.error(`ERROR: Unable to create the validation function output directory: ${ex}`);

  process.exit(errorStatus);
}

try {
  fs.writeFileSync(outputFilename, validationFuncString, 'utf8');
} catch (ex) {
  console.error(`ERROR: Unable to write the validation function to the output file: ${ex}`);

  process.exit(errorStatus);
}

console.info(`Validation function written to ${outputFilename}`);
